summary: Info of a specific connection
tags:
  - connections
operationId: connectionsFetchByNameAndEnvironment
parameters:
  - $ref: "../../parameters/path/connections/Name.yaml"
  - $ref: "../../parameters/path/connections/Environment.yaml"
responses:
  '200':
    description: Expected response to a valid request
    content:
      application/json:
        schema:
          $ref: "../../schemas/connections/ConnectionDto.yaml"
  '403':
    description: Expected response to a forbidden request
    content:
      application/json:
        schema:
          $ref: "../../schemas/response/ErrorResponse.yaml"
        example:
          timestamp: "2021-02-09T07:57:01.062+0000"
          status: 403
          error: "Forbidden"
          message: "Access denied"
          path: "/api/connections/"
  '404':
    description: Expected response to a un-existing connection



