type: object
properties:
  _embedded:
    type: object
    properties:
      scripts:
        type: array
        items:
          $ref: './EnvironmentDto.yaml'
  page:
    $ref: '../../schemas/pagination/PaginationProperties.yaml'