openapi: 3.0.1

info:
  title: IESI API
  license:
    name: MIT
    url: 'https://github.com/metadew/iesi-doc/blob/master/LICENSE'
  version: 0.6.0

servers:
  - url: 'http://localhost:8080/api'
    description: Generated server url

tags:
  - name: scripts
    description: Everything about scripts
  - name: impersonations
    description: Everything about impersonations
  - name: execution requests
    description: Everything about execution requests
  - name: environments
    description: Everything about environments
  - name: connections
    description: Everything about connections
  - name: components
    description: Everything about components
  - name: action-types
    description: Everything about action types
  - name: connection-types
    description: Everything about connection types
  - name: component-types
    description: Everything about component types
  - name: users
    description: Everything about users
  - name: teams
    description: Everything about teams
  - name: datasets
    description: Everything about datasets
  - name: security_groups
    description: Everthing about security groups

paths:
  $ref: "./paths/_index.yaml"
components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  securitySchemes:
    $ref: "./securitySchemes/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"